#!/bin/bash
dir=$1

if [[ $# -lt 1 ]] ; then
  echo "usage: $0 YYYYMMDDHH"
  exit
fi
if [ ! -d $dir ]; then
  echo "./$dir not found"
  exit
fi

#cmd="ls -d"
cmd="rm -rf "
cd $dir
$cmd 
$cmd anal_conv_gsi
$cmd anal_conv_gsi_spinup
$cmd fcst_fv3lam
$cmd fcst_fv3lam_spinup
$cmd nonvar_cldanl
$cmd nonvar_cldanl_spinup
$cmd process_bufr
$cmd process_bufr_spinup
$cmd process_radarref
$cmd process_radarref_spinup
$cmd FV3GFS
$cmd lbcs
$cmd ics
$cmd postprd


####11G     postprd
